---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent-aws-cloudwatch
  namespace: eck-poc
spec:
  version: 9.0.3
  elasticsearchRefs:
  - name: es-eck
    namespace: eck-poc
  deployment:
    replicas: 0
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
  config:
    inputs:
      - name: system-default
        revision: 1
        type: system/metrics
        use_output: default
        meta:
          package:
            name: system
            version: 0.9.1
        data_stream:
          namespace: default
        streams:
          - id: system/metrics-system.cpu
            data_stream:
              dataset: system.cpu
              type: metrics
            metricsets:
              - cpu
            cpu.metrics:
              - percentages
              - normalized_percentages
            period: 10s
