---
apiVersion: v1
kind: Namespace
metadata:
  name: eck-poc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
allowVolumeExpansion: true
parameters:
  type: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: Secret
metadata:
  name: es-telemetry-token
  namespace: eck-poc
type: Opaque
stringData:
  telemetry.secret_token: 8Frl70nJHH3S86c4hU7q6YV0
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-telemetry-token
  namespace: eck-poc
type: Opaque
stringData:
  elastic.apm.secretToken: 8Frl70nJHH3S86c4hU7q6YV0
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: eck-poc
  name: es-eck
spec:
  version: 9.0.2
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: es-eck
          namespace: eck-poc
    logs:
      elasticsearchRefs:
        - name: es-eck
          namespace: eck-poc
  secureSettings:
    - secretName: es-telemetry-token
  http:
    service:
      spec:
        ports:
          - name: es-https
            protocol: TCP
            port: 9200
            targetPort: 9200
          - name: es-transport
            protocol: TCP
            port: 9300
            targetPort: 9300
        type: ClusterIP
  nodeSets:
    - name: hot
      count: 2
      config:
        node.roles: ["data_hot", "ingest", "transform", "data_content","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        xpack.monitoring.collection.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-poc.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 8Gi
                cpu: 2
              limits:
                memory: 8Gi
                cpu: 2
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: ebs-gp3

    - name: cold
      count: 1
      config:
        node.roles: ["data_cold","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        xpack.monitoring.collection.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-poc.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: 2
                limits:
                  memory: 8Gi
                  cpu: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 12Gi
            storageClassName: ebs-gp3

    - name: frozen
      count: 1
      config:
        node.roles: ["data_frozen","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        xpack.searchable.snapshot.shared_cache.size: 15GB
        xpack.monitoring.collection.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-poc.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: 2
                limits:
                  memory: 8Gi
                  cpu: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: ebs-gp3

    - name: master-only
      count: 1
      config:
        node.roles: ["master","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        xpack.monitoring.collection.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-poc.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 2Gi
                cpu: 1
              limits:
                memory: 2Gi
                cpu: 1
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: ebs-gp3

    - name: ml
      count: 1
      config:
        node.roles: ["ml", "transform","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.ml.enabled: true
        xpack.security.audit.enabled: true
        xpack.monitoring.collection.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-poc.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 8Gi
                cpu: 2
              limits:
                memory: 8Gi
                cpu: 2
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: ebs-gp3

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: eck-poc
  name: kibana-eck
  labels:
    app: kibana
spec:
  version: 9.0.2
  count: 1
  http:
    service:
      spec:
        ports:
          - name: kibana-https
            protocol: TCP
            port: 443
            targetPort: 5601
        type: LoadBalancer
  secureSettings:
    - secretName: kibana-telemetry-token
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest
    monitoring.ui.elasticsearch.username: monitoring
    monitoring.ui.elasticsearch.password: Changed!Monitor
    elastic:
      apm:
        active: true
        serverUrl: https://apm-eck-apm-http.eck-poc.svc:8200
        secretToken: 8Frl70nJHH3S86c4hU7q6YV0
        centralConfig: true
        breakdownMetrics: true
        transactionSampleRate: 1
        verifyServerCert: false
        environment: dev
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
        namespace: eck-poc
    logs:
      elasticsearchRefs:
      - name: es-eck
        namespace: eck-poc
  elasticsearchRef:
    name: es-eck
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata: 
  namespace: eck-poc
  name: apm-eck
spec:
  version: 9.0.2
  count: 1
  elasticsearchRef:
    name: es-eck
  kibanaRef:
    name: kibana-eck
  http:
    service:
      spec:
        type: ClusterIP
  config:
    apm-server:
      auth:
        anonymous:
          enabled: true
          allow_agent:
            - java
            - rum-js
            - js-base
            - iOS/swift
            - python
            # added java for elasticsearch to skip token configuration
        api_key:
          enabled: false
          limit: 100
      default_service_environment: eck
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-internal-https
  namespace: eck-poc
spec:
  ports:
    - name: elasticsearch-https
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: es-eck
    elasticsearch.k8s.elastic.co/node-ingest: "true"
  type: ClusterIP
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent-aws-cloudwatch
  namespace: eck-poc
spec:
  version: 9.0.2
  elasticsearchRefs:
  - name: es-eck
    namespace: eck-poc
  deployment:
    replicas: 0
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
  config:
    inputs:
      - name: system-default
        revision: 1
        type: system/metrics
        use_output: default
        meta:
          package:
            name: system
            version: 0.9.1
        data_stream:
          namespace: default
        streams:
          - id: system/metrics-system.cpu
            data_stream:
              dataset: system.cpu
              type: metrics
            metricsets:
              - cpu
            cpu.metrics:
              - percentages
              - normalized_percentages
            period: 10s

