---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: eck-poc
  name: kibana-eck
  labels:
    app: kibana
spec:
  version: 9.0.3
  count: 1
  http:
    service:
      spec:
        ports:
          - name: kibana-https
            protocol: TCP
            port: 443
            targetPort: 5601
        type: LoadBalancer
  #secureSettings:
  #  - secretName: kibana-telemetry-token
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest
  #  monitoring.ui.elasticsearch.username: monitoring
  #  monitoring.ui.elasticsearch.password: Changed!Monitor
    elastic:
      apm:
        active: true
        serverUrl: https://apm-eck-apm-http.eck-poc.svc:8200
        centralConfig: true
        breakdownMetrics: true
        transactionSampleRate: 1
        verifyServerCert: false
        environment: dev
  #monitoring:
  #  metrics:
  #    elasticsearchRefs:
  #    - name: es-eck
  #      namespace: eck-poc
  #  logs:
  #    elasticsearchRefs:
  #    - name: es-eck
  #      namespace: eck-poc
  elasticsearchRef:
    name: es-eck
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
