---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata: 
  namespace: eck-demo
  name: apm-eck
spec:
  version: 9.0.3
  count: 1
  elasticsearchRef:
    name: es-eck
  kibanaRef:
    name: kibana-eck
  http:
    service:
      spec:
        type: ClusterIP
  config:
    apm-server:
      auth:
        anonymous:
          enabled: true
          allow_agent:
            - java
            - rum-js
            - js-base
            - iOS/swift
            - python
            - nodejs
            # added java for elasticsearch to skip token configuration, add nodejs for kibana to skip token configuration
        api_key:
          enabled: false
          limit: 100
      rum:
        enabled: true
      default_service_environment: eck
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
