---
apiVersion: v1
kind: Namespace
metadata:
  name: eck-demo
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
allowVolumeExpansion: true
parameters:
  type: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

