---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: eck-demo
  name: es-eck
spec:
  version: 9.0.3
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
      # namespace: eck-demo
    logs:
      elasticsearchRefs:
      - name: es-eck
      # namespace: eck-demo
  # secureSettings:
  #  - secretName: es-telemetry-token
  # http:
  #  service:
  #   spec:
  #     type: ClusterIP
  remoteClusters:
  - name: es-demo
    elasticsearchRef:
      name: es-demo
      namespace: eck-demo
  nodeSets:
    - name: hot
      count: 1
      config:
        node.roles: ["data_hot", "remote_cluster_client","ml","ingest"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 0.1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        metadata:	
            creationTimestamp: null
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 8Gi
                cpu: "2"
              limits:
                memory: 8Gi
                cpu: "2"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 75Gi
          storageClassName: ebs-gp3

    - name: cold
      count: 1
      config:
        node.roles: ["data_cold", "data_content", "remote_cluster_client","master","ingest","ml"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 0.1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        metadata:	
            creationTimestamp: null
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: "2"
                limits:
                  memory: 8Gi
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: ebs-gp3

    - name: frozen
      count: 1
      config:
        node.roles: ["data_frozen","remote_cluster_client","ml","transform","ingest"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 0.1
            breakdown_metrics: true
            service_name: elasticsearch
        xpack.searchable.snapshot.shared_cache.size: 23GB
      podTemplate:
        metadata:	
            creationTimestamp: null
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 8Gi
                  cpu: "2"
                limits:
                  memory: 8Gi
                  cpu: "2"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: ebs-gp3

    #- name: master-only
    #  count: 1
    #  config:
    #    node.roles: ["master","remote_cluster_client"]
    #    node.store.allow_mmap: false
    #   xpack.security.audit.enabled: true
    #    telemetry:
    #      tracing:
    #        enabled: true
    #      agent:
    #        server_url: https://apm-eck-apm-http.eck-demo.svc:8200
    #        verify_server_cert: false
    #        environment: dev
    #        transaction_sample_rate: 1
    #        breakdown_metrics: true
    #        service_name: elasticsearch
    #  podTemplate:
    #    spec:
    #      containers:
    #      - name: elasticsearch
    #        resources:
    #          requests:
    #            memory: 2Gi
    #            cpu: 1
    #          limits:
    #            memory: 2Gi
    #            cpu: 1
    #  volumeClaimTemplates:
    #  - metadata:
    #      name: elasticsearch-data
    #   spec:
    #      accessModes:
    #      - ReadWriteOnce
    #      resources:
    #        requests:
    #          storage: 5Gi
    #      storageClassName: ebs-gp3

    #- name: ml
    #  count: 1
    #  config:
    #    node.roles: ["ml", "transform","remote_cluster_client"]
    #    node.store.allow_mmap: false
    #    xpack.ml.enabled: true
    #    xpack.security.audit.enabled: true
    #    telemetry:
    #      tracing:
    #        enabled: true
    #      agent:
    #        server_url: https://apm-eck-apm-http.eck-demo.svc:8200
    #        verify_server_cert: false
    #        environment: dev
    #        transaction_sample_rate: 1
    #        breakdown_metrics: true
    #        service_name: elasticsearch
    #  podTemplate:
    #    spec:
    #      containers:
    #      - name: elasticsearch
    #        resources:
    #          requests:
    #            memory: 8Gi
    #            cpu: 4
    #          limits:
    #            memory: 8Gi
    #            cpu: 4
    #  volumeClaimTemplates:
    #  - metadata:
    #      name: elasticsearch-data
    #    spec:
    #      accessModes:
    #      - ReadWriteOnce
    #      resources:
    #        requests:
    #          storage: 5Gi
    #      storageClassName: ebs-gp3
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: eck-demo
  name: es-demo
spec:
  version: 9.0.3
  remoteClusterServer:
    enabled: true
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
    logs:
      elasticsearchRefs:
      - name: es-eck
  nodeSets:
    - name: hot
      count: 1
      config:
        node.roles: ["data","master","ingest", "remote_cluster_client","ml"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: demo
            transaction_sample_rate: 0.1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 8Gi
                cpu: "2"
              limits:
                memory: 8Gi
                cpu: "2"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: ebs-gp3
