---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: eck-demo
spec:
  version: 8.17.5
  mode: fleet
  fleetServerEnabled: true
  elasticsearchRefs:
  - name: es-demo
  kibanaRef:
    name: kibana-demo
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
