---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: set-no-replica
  namespace: eck-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-rest-api
            image: curlimages/curl:latest
            command: [ "sh", "-c", "echo The password is: $ELASTIC_PASSWORD; sleep 3600" ]
            env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-eck-es-elastic-user
                  key: elastic
            # args:

          restartPolicy: Never
