---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: set-no-replica
  namespace: eck-demo
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-rest-api
            image: curlimages/curl:latest
            command: ["sleep"]
            env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-eck-es-elastic-user
                  key: elastic
            args:
              - 3600
              - -X
              - PUT
              - -sSL
              - -k
              - https://es-eck-es-internal-http.eck-demo.svc:9200/*/_settings
              - -u
              - elastic:$PASSWORD
              - -H
              - "Content-Type: application/json"
              - -d
              - '{"number_of_replicas": 0}'
          restartPolicy: Never
