---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-demo
  namespace: eck-demo
spec:
  version: 8.18.4
  count: 1
  elasticsearchRefs:
  - name: es-demo
    clusterName: demo
  config:
    pipeline.workers: 4
    log.level: debug
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          mutate {
            add_field => {
              "pass_thru" => "logstash_demo"
            }
          }
          
          # Mask internal IP addresses (third segment)
          # Matches private IP ranges: 10.x.x.x, 172.16-31.x.x, 192.168.x.x
          mutate {
            gsub => [
              "message", "(?<=\b(?:10|172\.(?:1[6-9]|2[0-9]|3[01])|192\.168)\.)[0-9]{1,3}(?=\.[0-9]{1,3}\b)", "XXX"
            ]
          }
          
          # Mask credit card numbers (keep first 2 and last 4 digits)
          # Matches 13-19 digit credit card numbers with optional spaces/dashes
          mutate {
            gsub => [
              "message", "\b([0-9]{2})[0-9\s\-]*([0-9]{4})\b", "\1XXXXXXXXXX\2"
            ]
          }
          
          # Mask Singapore NRIC (keep last 4 characters)
          # Format: S/T/F/G + 7 digits + letter (e.g., S1234567A)
          mutate {
            gsub => [
              "message", "\b[STFG][0-9]{7}[A-Z]\b", "SXXXXXXX\4"
            ]
          }
        }
        
        output {
          elasticsearch {
            hosts => [ "${DEMO_ES_HOSTS}" ]
            user => "${DEMO_ES_USER}"
            password => "${DEMO_ES_PASSWORD}"
            ssl_certificate_authorities => "${DEMO_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  podTemplate:
    spec:
      volumes:
      - name: logstash-data
        emptyDir: {}
  services:
    - name: beats
      service:
        spec:
          type: ClusterIP
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
