---
apiVersion: v1
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    kind: PersistentVolumeClaim
    name: logstash-data-logstash-demo-ls-0
    namespace: eck-demo
  storageClassName: ebs-gp3
  volumeMode: Filesystem
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-demo
  namespace: eck-demo
spec:
  version: 8.18.4
  count: 1
  elasticsearchRefs:
  - name: es-demo
    clusterName: demo
  config:
    pipeline.workers: 4
    log.level: debug
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "${DEMO_ES_HOSTS}" ]
            user => "${DEMO_ES_USER}"
            password => "${DEMO_ES_PASSWORD}"
            ssl_certificate_authorities => "${DEMO_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
#  podTemplate:
#    spec:
#      volumes:
#      - name: logstash-data
#        emptyDir: {}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: logstash-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
        storageClassName: ebs-gp3
#  volumeClaimTemplates:
#  - metadata:
#      name: logstash-data
#    kind: PersistentVolume
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      resources:
#        requests:
#          storage: 2Gi
#      storageClassName: ebs-gp3
#      volumeName: logstash-data
