---
apiVersion: v1
kind: Namespace
metadata:
  name: eck-demo
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
allowVolumeExpansion: true
parameters:
  type: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-internal-https
  namespace: eck-demo
spec:
  ports:
    - name: elasticsearch-https
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: es-eck
    elasticsearch.k8s.elastic.co/node-ingest: "true"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-eck-https
  namespace: eck-demo
spec:
  ports:
    - name: kibana-eck-https
      protocol: TCP
      port: 443
      targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana-eck
  type: LoadBalancer
