---
apiVersion: v1
kind: Namespace
metadata:
  name: eck-test
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
allowVolumeExpansion: true
parameters:
  type: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-eck-https
  namespace: eck-test
spec:
  ports:
    - name: kibana-eck-https
      protocol: TCP
      port: 443
      targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana-eck
  type: LoadBalancer
