---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: eck-demo
  name: es-eck
spec:
  version: 8.18.4
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
    logs:
      elasticsearchRefs:
      - name: es-eck
  nodeSets:
    - name: hot
      count: 15
      config:
        node.roles: ["data_hot", "remote_cluster_client","ml","ingest"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
        xpack.security.http.ssl.client_authentication: none
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 0.1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 3Gi
                cpu: "1"
              limits:
                memory: 3Gi
                cpu: "1"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: ebs-gp3

    - name: master-only
      count: 1
      config:
        node.roles: ["master","remote_cluster_client"]
        node.store.allow_mmap: false
       xpack.security.audit.enabled: true
        telemetry:
          tracing:
            enabled: true
          agent:
            server_url: https://apm-eck-apm-http.eck-demo.svc:8200
            verify_server_cert: false
            environment: dev
            transaction_sample_rate: 1
            breakdown_metrics: true
            service_name: elasticsearch
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 2Gi
                cpu: 1
              limits:
                memory: 2Gi
                cpu: 1
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
       spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: ebs-gp3
