---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: eck-demo
  name: es-eck
spec:
  version: 8.19.2
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
    logs:
      elasticsearchRefs:
      - name: es-eck
  nodeSets:
    - name: hot
      count: 15
      config:
        node.roles: ["data_hot", "remote_cluster_client","ml","ingest"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 3Gi
                cpu: "1"
              limits:
                memory: 3Gi
                cpu: "1"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
          storageClassName: ebs-gp3

    - name: master-only
      count: 3
      config:
        node.roles: ["master","remote_cluster_client"]
        node.store.allow_mmap: false
        xpack.security.audit.enabled: true
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 1Gi
                cpu: 0.5
              limits:
                memory: 1Gi
                cpu: 0.5
