---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: eck-demo
  name: kibana-eck
  labels:
    app: kibana
spec:
  version: 8.19.2
  count: 1
  config:
    xpack.security.audit.enabled: true
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-eck
    logs:
      elasticsearchRefs:
      - name: es-eck
  elasticsearchRef:
    name: es-eck
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 4Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 1
